# Generated by Django 4.1 on 2023-12-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
