# Generated by Django 4.1 on 2023-12-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_accepted_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='accepted_terms',
            new_name='terms_accepted',
        ),
    ]
