# Generated by Django 4.1 on 2023-11-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
