name: Python application

on:
  push:
    branches:
      - master
      - feature/workflow

jobs:
  build:
    strategy:
      matrix:
        pyversion: ['3.9']

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.9-alpine
        env:
          POSTGRES_USER: decide
          POSTGRES_PASSWORD: decide
          POSTGRES_DB: decide
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      vnc: 
        image: dorowu/ubuntu-desktop-lxde-vnc:latest
        ports:
          - "5900:5900"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{matrix.pyversion}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.pyversion}}
    - name: psycopg2 prerequisites
      run: sudo apt-get install libpq-dev
    - name: Wait for VNC to be ready
      run: sleep 10
  
   
    - name: Install dependencies and config
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install codacy-coverage
        cp decide/local_settings.gactions.py decide/local_settings.py
    - name: Run migrations (unnecessary)
      run: |
        cd decide
        python manage.py makemigrations
        python manage.py migrate

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: |
        cd docker
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/decide-single-velazquez:latest .

    - name: Push to Docker Hub
      run: |
        cd docker
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/decide-single-velazquez:latest
    
    - name: Render deploy
      run: |
        curl https://api.render.com/deploy/srv-clusip6g1b2c73cbagug?key=YYHmyVhR3Ko


