name: CI

on:
  push:


jobs:
  build:
    strategy:
      matrix:
        pyversion: ['3.8','3.9']

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.18-bullseye
        env:
          POSTGRES_USER: decide
          POSTGRES_PASSWORD: decide
          POSTGRES_DB: decide
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      vnc: 
        image: dorowu/ubuntu-desktop-lxde-vnc:latest
        ports:
          - "5900:5900"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{matrix.pyversion}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.pyversion}}
    - name: psycopg2 prerequisites
      run: sudo apt-get install libpq-dev
    - name: Wait for VNC to be ready
      run: sleep 10
    - name: dependencies for selenium
      run: |
        sudo apt-get install python3-tk
        sudo apt-get install gnome-screenshot
        sudo apt-get install -y chromium-browser
  
   
    - name: Install dependencies and config
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install codacy-coverage
        cp decide/local_settings.gactions.py decide/local_settings.py
    - name: Run migrations (unnecessary)
      run: |
        cd decide
        python manage.py makemigrations
        python manage.py migrate
    - name: Run tests
      run: |
        cd decide
        coverage run --branch --source=. ./manage.py test --keepdb 
        coverage xml 

    - name: Check commit message format
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
        COMMIT_MESSAGE=$(git log --format="%s" -n 1 ${{ github.sha }})
        PATTERN="^(feat:|fix:|docs:|style:|refactor:|test:|[A-Z][a-z]*:)"
        
        if [[ ! "$COMMIT_MESSAGE" =~ "Merge pull request" ]]; then
          if [[ ! "$COMMIT_MESSAGE" =~ $PATTERN ]]; then
            echo "Error: El mensaje de commit '$COMMIT_MESSAGE' no sigue el formato esperado."
            exit 1
          fi
        else
          echo "Skipping commit message verification for pull request merge commit."
        fi
        else
          echo "Skipping commit message verification for pull request."
        fi

    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: decide/coverage.xml