name: Python application

on:
  push:


jobs:
  build:
    strategy:
      matrix:
        pyversion: ['3.8','3.9']

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.18-bullseye
        env:
          POSTGRES_USER: decide
          POSTGRES_PASSWORD: decide
          POSTGRES_DB: decide
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      vnc: 
        image: dorowu/ubuntu-desktop-lxde-vnc:latest
        ports:
          - "5900:5900"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{matrix.pyversion}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.pyversion}}


    - name: Check commit message format
      run: |
        COMMIT_MESSAGES=$(git log --format=%s 1a546b6600ad78eb1ace321766cfc573af75c26a..${{ github.sha }})
        PATTERN="^(feat:|fix:|docs:|style:|refactor:|test:|[A-Z][a-z]*:)"
        IFS=$'\n' # Configura el separador interno para manejar espacios en mensajes

        for COMMIT_MESSAGE in "${COMMIT_MESSAGES}"; do
          if [[ ! "$COMMIT_MESSAGE" =~ "Merge pull request" ]]; then
            if [[ ! "$COMMIT_MESSAGE" =~ $PATTERN ]]; then
              echo "Error: El mensaje de commit '$COMMIT_MESSAGE' no sigue el formato esperado."
              exit 1
            else
              echo "Commit message '$COMMIT_MESSAGE' follows the format."
            fi
          else
            echo "Skipping commit message verification for pull request merge commit."
          fi
        done